# Generated by Django 2.2.3 on 2019-08-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='area',
            field=models.CharField(blank=True, choices=[('서울특별시', '서울특별시'), ('부산광역시', '부산광역시'), ('세종특별시', '세종특별시'), ('충청북도', '충청북도'), ('충청남도', '충청남도'), ('전라북도', '전라북도'), ('전라남도', '전라남도'), ('대구광역시', '대구광역시'), ('제주특별시', '제주특별시'), ('경상북도', '경상북도'), ('경상남도', '경상남도')], max_length=50),
        ),
        migrations.AlterField(
            model_name='post_image',
            name='images',
            field=models.ImageField(blank=True, upload_to='image/post_image/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='qna_image',
            name='images',
            field=models.ImageField(blank=True, upload_to='image/qna_image/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='review_image',
            name='images',
            field=models.ImageField(blank=True, upload_to='image/review_image/%Y/%m/%d'),
        ),
    ]
