# Generated by Django 2.1.7 on 2019-08-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qna',
            name='confirm',
        ),
        migrations.AddField(
            model_name='review',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
