# Generated by Django 2.1.7 on 2019-08-07 08:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='choose_date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='post',
            name='strat_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
