# Generated by Django 2.1.7 on 2019-08-05 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190805_0658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qna',
            old_name='text',
            new_name='context',
        ),
    ]
